name: CI/CD Pipeline

on:
  push:
    branches:
      - feature-branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Linting
      run: npm run lint

    - name: Build
      run: npm run build

    - name: Run unit tests
      run: npm run test

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t giselle06/web-application:latest .

    - name: Push Docker image
      run: docker push giselle06/web-application:latest
